Update pom.xml in preparation of ADO pipeline
microsoft/credential-secure-storage-for-java pull request #25
Opened 2024-09-17 12:58 UTC by ivanTrogrlic

2024-09-17 13:03 UTC, ivanTrogrlic commented
@microsoft-github-policy-service agree company="Microsoft"

2024-09-17 13:29 UTC, abyss638 requested changes

2024-09-17 13:29 UTC, abyss638 commented on pom.xml
> +    <project.version>${project.version}</project.version>
Is it really needed?

2024-09-17 13:29 UTC, abyss638 commented on .config/tsaoptions.json
I don't think this file needed?

2024-09-17 13:29 UTC, abyss638 commented on pom.xml
> +  <version>1.0.3</version>
Please update version in sample pom.xml

2024-09-17 13:33 UTC, abyss638 commented on azure-pipelines.yml
Please delete deploy.yml file in workflows as well

2024-09-18 07:00 UTC, ivanTrogrlic commented on pom.xml
> +    <project.version>${project.version}</project.version>
Removed

2024-09-18 07:00 UTC, ivanTrogrlic commented on .config/tsaoptions.json
Removed

2024-09-18 07:00 UTC, ivanTrogrlic commented on pom.xml
> +  <version>1.0.3</version>
Updated

2024-09-18 07:01 UTC, ivanTrogrlic commented on azure-pipelines.yml
Removed

2024-09-18 10:32 UTC, merged